### ISSUE TITLE
Easy Provision and Deploy

### ISSUE THREAD

**Issue by elorest** [amber-crystal/amber-cmd#38]
The deploy command will allow for 2 things.

1. Provisioning of servers on digital ocean and later most vps providers. (> 7 minutes)
  a. `amber deploy --init -s [do, aws, etc] --key [your_api_key] [production, staging, etc]`
  b.  Sets up server returns deploy key for you to add to github/gitlab.
  c. Returns ssh login string if needed.
2. Deploys current version or tag from git to server and returns url of working server. (~ 50 seconds)
  a. `amber deploy -t [optional-tag] -b [optional branch, master default] [deploy, production, etc]
  b. Checks out code migrates, resets appropriate docker containers.
  c. Returns working url and ssh login string.

**Comment by drujensen** [comment]
resolved by #45
