### ISSUE TITLE
Command to deploy to cloud services.

### ISSUE THREAD

**Issue by eliasjpr** [amber-crystal/amber-cmd#4]
> As a Developer I would like to deploy my project from the command line.

```
amber deploy heroku -u <user> -p <pass> -r <heroku remote project>
amber deploy digitalocean -u <user> -p <pass> -r <digitalocean remote project>
```

**Comment by eliasjpr** [comment]
PR https://github.com/Amber-Crystal/amber_cmd/pull/12

**Comment by drujensen** [comment]
@eliasjpr is this resolved?  trying to close out tickets and move over any that are left outstanding

**Comment by eliasjpr** [comment]
We can circle back later to this. This is more of a wish list now
