### ISSUE TITLE
Validation error-messages in web-browser displayed wrong?

### ISSUE THREAD

**Issue by davidbe** [amber-crystal/amber-cmd#66]
When I write model-validations, with models generated by scaffold, when validations are not met, errors are not shown correct in browser.

I scaffold generated `user` which generated:
```
require "granite_orm/adapter/sqlite"

class User < Granite::ORM 
  adapter sqlite

  # id : Int64 primary key is created for you
  field username : String
  field email : String
  field password_digest : String

end
```
I add this to require a username:
`  validate :username, "is required", -> (this : User) { this.username != "" }
`

When I try to input a user without a username, the "new"-page is shown again with an error that validations aren't met, but only with "#" as text when "username is required" is expected.

I fiddled around with `_form.ecr` which is also generated. Errors are displayed with:

```
<%- if user.errors %>
  <ul class="errors">
  <%- user.errors.each do |error| %>
    <li><%= error %></li>
  <%- end %>
  </ul>
<%- end %>
```
But this works:

```
<%- if user.errors %>
  <ul class="errors">
  <%- user.errors.each do |error| %>
      <li><%= "#{error.field} #{error.message}" %></li>
  <%- end %>
  </ul>
<%- end %>
```

I'm wondering, should generated template be adjusted?

**Comment by drujensen** [comment]
error.to_s will properly display the field and message. We should fix this in the template. 

Can you create a PR?
